### ISSUE TITLE
Allow for a NMHC mrn to be cleared out.

### ISSUE THREAD

**Issue by mgurley** [NUARIG/all-of-us-helper#106]

**Comment by joycehonu** [comment]
Mike, this predates Queenie, should we close?

**Comment by ybushmanova** [comment]
@OSNorthwestern is this still relevant?

**Comment by OSNorthwestern** [comment]
Hi @ybushmanova, I believe this is still relevant. I think ticket was about MRN removal once pushed to ST? It isn't biggest issue for us if asking for removal is okay with you.

**Comment by pshum1** [comment]
hi @NiviyaGeorge is this ticket still relevant for us to look in to?

**Comment by NiviyaGeorge** [comment]
@pshum1, I am not sure what this ticket is about. I think we still use the MRN in ST to look up participant. I thought MRN was one of the field match to get ST status update ["Identified" to "interested" ] which is then updated in the REDCap MyChart.
