### ISSUE TITLE
Explore reversing the synch of patients to be initiated from REDCap instead of from the Helper.

### ISSUE THREAD

**Issue by mgurley** [NUARIG/all-of-us-helper#134]
If we can fire a webhook from REDCap upon every add of a record to the REDCap project, we can make the integration of REDCap and the Helper realtime.

**Comment by mgurley** [comment]
REDCap team told us our REDCap instance won't support data entry triggers.

**Comment by ybushmanova** [comment]
We can look into manual triggers. Redcap supports advanced link, that can initiate request to the Helper App

**Comment by mgurley** [comment]
NU IT does not support this.
