### ISSUE TITLE
Follow-Up with Study Tracker Team (ARIG 12.12.19)

### ISSUE THREAD

**Issue by qkyho** [NUARIG/all-of-us-helper#153]
What to do in case of withdrawn core participants who re-enroll?  Does a removal replicate across all systems (specifically Study Tracker)?  Can a participant/1 MRN/multiple PMI IDs be registered multiple times in Study Tracker?

**Comment by qkyho** [comment]
Asked Laura.  She will follow-up with email to Jalpa.

**Comment by ybushmanova** [comment]
@OSNorthwestern is this still relevant?

**Comment by OSNorthwestern** [comment]
Not currently relevant.
