### ISSUE TITLE
Automate API File Process To Post Every Monday Morning At 9AM

### ISSUE THREAD

**Issue by OSNorthwestern** [NUARIG/all-of-us-helper#204]
We generate a report that has a record number that goes above 10,000 because of this we will need a file to be posted every Monday at 9AM.

**Comment by ybushmanova** [comment]
Request app access to shared folder

**Comment by ybushmanova** [comment]
Waiting on #213

**Comment by OSNorthwestern** [comment]
Add registration_status to HealthPro API file
