### ISSUE TITLE
Helper App: EMPI Ethnicity Not Populating

### ISSUE THREAD

**Issue by OSNorthwestern** [NUARIG/all-of-us-helper#209]
In Helper App, when we assign a MRN to a participant, their ethnicity is not populating into their Helper App profile even though there is an ethnicity listed in their EMPI.

**Comment by ybushmanova** [comment]
Epic has new values for Ethnicity/race that are not yet mapped in StudyTracker either. Pending resolution.

**Comment by ybushmanova** [comment]
StudyTracker implemented fix to map new EMPI ethnicity and race values
