### ISSUE TITLE
Import new fields from HealthPro API

### ISSUE THREAD

**Issue by ybushmanova** [NUARIG/all-of-us-helper#212]
Ask the DRC for the latest documentation of the HealthPro API/CSV mapping

**Comment by OSNorthwestern** [comment]
Hi Yulia, I've reached out to them in the past. I can resend the email link to you.

[https://www.aoucollaborations.net/x/dgCIP](https://urldefense.com/v3/__https://nam12.safelinks.protection.outlook.com/?url=https*3A*2F*2Fwww.aoucollaborations.net*2Fx*2FdgCIP&data=05*7C01*7Cdrcsupport*40vumc.org*7C4ccc5a1ac0124431d55d08daa008ef39*7Cef57503014244ed8b83c12c533d879ab*7C0*7C0*7C637998257472857365*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000*7C*7C*7C&sdata=UY4R9FPQNaFvQJO1fUpiYYPub6vU5EOFcYRh*2F0uoQcI*3D&reserved=0__;JSUlJSUlJSUlJSUlJSUlJSUlJSUlJQ!!Dq0X2DkFhyF93HkjWTBQKhk!Va4GAMvO2DUQUAVpgHN6CPcUfQWcDuFniG-5ynCtvLFTBBnbFQOBXVlOiDRXsrWJsSlbXxQVthDj3ikL4MvzWJkU_tw3$)

**Comment by OSNorthwestern** [comment]
Oliver will send new needed fields to Yulia in an email.

**Comment by ybushmanova** [comment]
New fields to add

[AllOfUs new api fields.csv](https://github.com/NUARIG/all-of-us-helper/files/9870398/AllOfUs.new.api.fields.csv)
