### ISSUE TITLE
Submit For Next EHR Submission 

### ISSUE THREAD

**Issue by OSNorthwestern** [NUARIG/all-of-us-helper#214]
Highest Priority Item
Deadline 11/30/22

**Comment by ybushmanova** [comment]
Submitted all but notes, waiting on DRC to let us know how to fix notes.

**Comment by ybushmanova** [comment]
DRC came back with explanation, we'll need to escabe double quotes in the file. Prasanth will be working on changes and we'll try resubmitting next week.
