### ISSUE TITLE
Change EHR Inclusion Logic To Include Biospecimen Location: Unset

### ISSUE THREAD

**Issue by OSNorthwestern** [NUARIG/all-of-us-helper#221]
Current EHR Inclusion Logic

(deactivation_status: '0'
AND
withdrawal_status: '0'
AND
participant_status: 'Core Participant'
AND
biospecimens_location: 'nwfeinberggalter' OR nwdelnorhospital' OR 'nwvernonhillsicc' OR 'nwmedicinegrayslake' 
AND
general_consent_status: '1'
AND
ehr_consent_status: '1'
AND
(
algorithm_validation = 'yes'
OR
manual_validation = 'yes'

Proposed Updated EHR Inclusion Logic

(deactivation_status: '0'
AND
withdrawal_status: '0'
AND
participant_status: 'Core Participant'
AND
biospecimens_location: 'nwfeinberggalter' OR nwdelnorhospital' OR 'nwvernonhillsicc' OR 'nwmedicinegrayslake' **_**OR UNSET** (Add this piece)_** 
AND
general_consent_status: '1'
AND
ehr_consent_status: '1'
AND
(
algorithm_validation = 'yes'
OR
manual_validation = 'yes'

**Comment by ybushmanova** [comment]
@NiviyaGeorge any updates on this? Last Time I've heard about this change it was put on hold

**Comment by NiviyaGeorge** [comment]
> @NiviyaGeorge any updates on this? Last Time I've heard about this change it was put on hold

We are still waiting for IRB approval on the talking points. Staff have to call participants to verify.

**Comment by NiviyaGeorge** [comment]
Week of July 17th: AoU Staff will start with MRN verification through Phone calls.
