### ISSUE TITLE
Add New Fields to the HealthPro WQ CSV Api File 

### ISSUE THREAD

**Issue by NiviyaGeorge** [NUARIG/all-of-us-helper#250]
Current WQ CSV Api File do not have the fields listed below. We will have to make sure these fields are generated on our WQ report. 
 Fields need to be added to the WQ CSV API File: 
1. Health Data Stream Sharing  Status
2. Health Data Stream Sharing Date
3. Emotional Health History and Well-being PPI Survey Complete
4. Emotional Health History and Well-being PPI Survey Completion Date
5. Behavioral Health and Personality PPI Survey Complete
6. Behavioral Health and Personality PPI Survey Completion Date

**Comment by NiviyaGeorge** [comment]
@pshum1 any updates on adding new columns to the HealthPro WQ CSV file?

**Comment by pshum1** [comment]
> @pshum1 any updates on adding new columns to the HealthPro WQ CSV file?

@NiviyaGeorge started working on it this week! Should be up by next week

**Comment by pshum1** [comment]
Hi @NiviyaGeorge! I was looking through the API response that we use to build the healthpro entries and was only able to find entries for Emotional Health History and Well-being PPI Survey Complete (questionnaireOnEmotionalHealthHistoryAndWellBeing) and Behavioral Health and Personality PPI Survey Complete (questionnaireOnBehavioralHealthAndPersonality). Are you able to identify the other fields from this sample:

"resource" => {
        "participantId" => "P493690429", "biobankId" => "A284147345", "firstName" => "Braunz", "middleName" => "D", "lastName" => "Williams", "zipCode" => "60619", "streetAddress" => "1133 E 83rd St", "phoneNumber" => "3127520020", "primaryLanguage" => "en", "dateOfBirth" => "1993-11-05", "genderIdentity" => "UNSET", "deceasedStatus" => "UNSET", "hpoId" => "ILLINOIS", "enrollmentStatus" => "INTERESTED", "enrollmentStatusV3_0" => "PARTICIPANT", "enrollmentStatusParticipantV3_0Time" => "2017-11-30T21:27:37", "consentCohort" => "COHORT_1", "cohort2PilotFlag" => "UNSET", "ehrStatus" => "UNSET", "isEhrDataAvailable" => false, "wasEhrDataAvailable" => false, "clinicPhysicalMeasurementsStatus" => "UNSET", "selfReportedPhysicalMeasurementsStatus" => "UNSET", "numberDistinctVisits" => 0, "signUpTime" => "2017-11-30T21:14:57", "withdrawalStatus" => "NOT_WITHDRAWN", "withdrawalReason" => "UNSET", "suspensionStatus" => "NOT_SUSPENDED", "participantOrigin" => "vibrent", "patientStatus" => [], "consentForStudyEnrollment" => "SUBMITTED", "consentForStudyEnrollmentTime" => "2017-11-30T21:27:40", "consentForStudyEnrollmentAuthored" => "2017-11-30T21:27:37", "consentForStudyEnrollmentFirstYesAuthored" => "2017-11-30T21:27:37", "consentForElectronicHealthRecords" => "UNSET", "ehrConsentExpireStatus" => "UNSET", "consentForDvElectronicHealthRecordsSharing" => "UNSET", "consentForGenomicsROR" => "UNSET", "consentForCABoR" => "UNSET", "consentForEtM" => "UNSET", "questionnaireOnOverallHealth" => "UNSET", "questionnaireOnLifestyle" => "UNSET", "questionnaireOnTheBasics" => "UNSET", "questionnaireOnHealthcareAccess" => "UNSET", "questionnaireOnMedicalHistory" => "UNSET", "questionnaireOnMedications" => "UNSET", "questionnaireOnFamilyHealth" => "UNSET", "questionnaireOnSocialDeterminantsOfHealth" => "UNSET", "questionnaireOnPersonalAndFamilyHealthHistory" => "UNSET", "questionnaireOnCopeMay" => "UNSET", "questionnaireOnCopeJune" => "UNSET", "questionnaireOnCopeJuly" => "UNSET", "questionnaireOnCopeNov" => "UNSET", "questionnaireOnCopeDec" => "UNSET", "questionnaireOnCopeFeb" => "UNSET", "questionnaireOnCopeVaccineMinute1" => "UNSET", "questionnaireOnCopeVaccineMinute2" => "UNSET", "questionnaireOnCopeVaccineMinute3" => "UNSET", "questionnaireOnCopeVaccineMinute4" => "UNSET", "questionnaireOnDnaProgram" => "UNSET", "questionnaireOnLifeFunctioning" => "UNSET", "numCompletedBaselinePPIModules" => 0, "numCompletedPPIModules" => 0, "biospecimenStatus" => "UNSET", "sampleStatus1SST8" => "UNSET", "sampleStatus2SST8" => "UNSET", "sampleStatus1SS08" => "UNSET", "sampleStatus1PST8" => "UNSET", "sampleStatus2PST8" => "UNSET", "sampleStatus1PS08" => "UNSET", "sampleStatus1HEP4" => "UNSET", "sampleStatus1ED04" => "UNSET", "sampleStatus1ED10" => "UNSET", "sampleStatus2ED10" => "UNSET", "sampleStatus1UR10" => "UNSET", "sampleStatus1UR90" => "UNSET", "sampleStatus1SAL" => "UNSET", "sampleStatus1SAL2" => "UNSET", "sample1SAL2CollectionMethod" => "UNSET", "sampleStatus1ED02" => "UNSET", "sampleStatus1CFD9" => "UNSET", "sampleStatus1PXR2" => "UNSET", "sampleStatusDV1SAL2" => "UNSET", "sampleStatus2ED02" => "UNSET", "sampleStatus2ED04" => "UNSET", "sampleOrderStatusDV1SAL2" => "UNSET", "sampleOrderStatus1SST8" => "UNSET", "sampleOrderStatus2SST8" => "UNSET", "sampleOrderStatus1SS08" => "UNSET", "sampleOrderStatus1PST8" => "UNSET", "sampleOrderStatus2PST8" => "UNSET", "sampleOrderStatus1PS08" => "UNSET", "sampleOrderStatus1HEP4" => "UNSET", "sampleOrderStatus1ED04" => "UNSET", "sampleOrderStatus1ED10" => "UNSET", "sampleOrderStatus2ED10" => "UNSET", "sampleOrderStatus1UR10" => "UNSET", "sampleOrderStatus1UR90" => "UNSET", "sampleOrderStatus1SAL" => "UNSET", "sampleOrderStatus1SAL2" => "UNSET", "sampleOrderStatus1ED02" => "UNSET", "sampleOrderStatus1CFD9" => "UNSET", "sampleOrderStatus1PXR2" => "UNSET", "sampleOrderStatus2ED02" => "UNSET", "sampleOrderStatus2ED04" => "UNSET", "numBaselineSamplesArrived" => 0, "samplesToIsolateDNA" => "UNSET", "retentionEligibleStatus" => "NOT_ELIGIBLE", "retentionType" => "UNSET", "onsiteIdVerificationType" => "UNSET", "onsiteIdVerificationVisitType" => "UNSET", "remoteIdVerificationOrigin" => "UNSET", "remoteIdVerificationStatus" => "UNSET", "everIdVerified" => "UNSET", "idVerificationOrigin" => "UNSET", "consentForNphModule1" => false, "nphWithdrawal" => false, "nphDeactivation" => false, "lastModified" => "2018-07-25T21:31:18", "questionnaireOnEmotionalHealthHistoryAndWellBeing" => "UNSET", "questionnaireOnBehavioralHealthAndPersonality" => "UNSET", "hasHeightAndWeight" => false, "consentForWearStudy" => "UNSET", "city" => "Chicago", "email" => "braunzwilliams@gmail.com", "race" => "UNSET", "aian" => false, "ageRange" => "25-34", "organization" => "ILLINOIS_NORTHWESTERN", "awardee" => "ILLINOIS", "income" => "UNSET", "recontactMethod" => "UNSET", "state" => "PIIState_IL", "education" => "UNSET", "sexualOrientation" => "UNSET", "language" => "UNSET", "sex" => "UNSET", "clinicPhysicalMeasurementsCreatedSite" => "UNSET", "clinicPhysicalMeasurementsFinalizedSite" => "UNSET", "biospecimenSourceSite" => "UNSET", "biospecimenCollectedSite" => "UNSET", "biospecimenProcessedSite" => "UNSET", "biospecimenFinalizedSite" => "UNSET", "site" => "UNSET", "enrollmentSite" => "UNSET", "physicalMeasurementsStatus" => "UNSET", "physicalMeasurementsCreatedSite" => "UNSET", "physicalMeasurementsFinalizedSite" => "UNSET", "physicalMeasurementsCollectType" => "UNSET", "relatedParticipants" => "UNSET", "isPediatric" => "UNSET", "questionnaireOnEnvironmentalHealth" => "UNSET", "remoteIdVerifiedOn" => "UNSET", "firstIdVerifiedOn" => "UNSET"
      }

Please let me know if you want to go through this together

**Comment by NiviyaGeorge** [comment]
Yes, Emotional Health History and Well-being PPI Survey Complete (questionnaireOnEmotionalHealthHistoryAndWellBeing) and Behavioral Health and Personality PPI Survey Complete (questionnaireOnBehavioralHealthAndPersonality) are new ones that we need. Other ones might be same ones as current with change in names. Can we go through this together? Thanks!

**Comment by ybushmanova** [comment]
@NiviyaGeorge here is a list of API fields available to us and database fields they are mapped to. I believe in CSV export you see database column names, not the API field names. Please let us know if there are any new fields we need to add, and iif/or the only issue is column mapping, we can rename the fields in exported CVS to match api fields

Api Field | Database column
-- | --
"withdrawalStatus" | withdrawal_status
"withdrawalTime" | withdrawal_date
"withdrawalReason" | withdrawal_reason
"participantId" | pmi_id
"hpoId" |  
"biobankId" | biobank_id
"firstName" | first_name
"lastName" | last_name
"dateOfBirth" | date_of_birth
"consentForStudyEnrollment" | general_consent_status
"consentForStudyEnrollmentAuthored" | general_consent_date
"consentForElectronicHealthRecords" | ehr_consent_status
"consentForElectronicHealthRecordsAuthored" | ehr_consent_date
"enrollmentStatus" | participant_status
"enrollmentStatusV3_0" |  
"ageRange" | age_range
"primaryLanguage" | language_of_general_consent
"organization" | paired_organization
"remoteIdVerificationStatus" |  
"everIdVerified" |  
"patientStatus" | patient_status
"awardee" |  
"recontactMethod" |  
"language" | language
"income" |  
"sex" | sex
"education" | education
"state" | state
"sexualOrientation" |  
"sampleOrderStatus1ED02" |  
"questionnaireOnCopeJuly" | questionnaire_on_cope_july
"sampleOrderStatus1CFD9" |  
"ehrConsentExpireStatus" | ehr_expiration_status
"selfReportedPhysicalMeasurementsStatus" | self_reported_physical_measurements_status
"sampleOrderStatus2ED04" |  
"consentForCABoR" | cabor_consent_status
"sampleStatus1SAL" | saliva_collected
"sampleStatus1PST8" | eight_ml_pst_collected
"sampleOrderStatus1PXR2" |  
"questionnaireOnCopeVaccineMinute2" | fall_minute_ppi_survey_complete
"sampleStatus1ED02" | two_ml_edta_collected
"sampleOrderStatus1UR90" |  
"sampleStatus2ED10" | second_10_ml_edta_collected
"sampleOrderStatus1HEP4" |  
"samplesToIsolateDNA" | samples_for_dna_received
"questionnaireOnHealthcareAccess" | access_ppi_survey_complete
"questionnaireOnLifeFunctioning" | questionnaire_on_life_functioning
"questionnaireOnOverallHealth" | health_ppi_survey_complete
"consentCohort" | consent_cohort
"questionnaireOnMedicalHistory" | hist_ppi_survey_complete
"sampleOrderStatus1PST8" |  
"sampleStatusDV1SAL2" |  
"questionnaireOnCopeDec" | cope_dec_ppi_survey_complete
"sampleStatus1HEP4" | four_ml_na_hep_collected
"cohort2PilotFlag" |  
"sampleOrderStatus1SST8" |  
"retentionEligibleStatus" | retention_eligible
"questionnaireOnCopeMay" | questionnaire_on_cope_may
"sampleOrderStatus1SS08" |  
"sampleStatus1UR10" | urine_10_ml_collected
"retentionType" | retention_status
"sampleOrderStatus1SAL2" |  
"sampleOrderStatus1SAL" |  
"questionnaireOnLifestyle" | lifestyle_ppi_survey_complete
"sampleOrderStatus1UR10" |  
"sampleStatus1ED04" | four_ml_edta_collected
"sampleStatus1SST8" | eight_ml_sst_collected
"sampleStatus1PXR2" | paxgene_rna_collected
"idVerificationOrigin" |  
"questionnaireOnEmotionalHealthHistoryAndWellBeing" |  
"clinicPhysicalMeasurementsStatus" |  
"sampleStatus2SST8" |  
"questionnaireOnCopeVaccineMinute1" | summer_minute_ppi_survey_complete
"questionnaireOnBehavioralHealthAndPersonality" |  
"suspensionStatus" | deactivation_status
"questionnaireOnMedications" |  
"sampleOrderStatus2ED10" |  
"consentForEtM" |  
"sampleOrderStatus1ED04" |  
"questionnaireOnCopeJune" | questionnaire_on_cope_june
"sampleStatus1ED10" | first_10_ml_edta_collected
"sampleOrderStatus1ED10" |  
"questionnaireOnCopeFeb" | cope_feb_ppi_survey_complete
"sampleStatus1PS08" |  
"consentForGenomicsROR" | consent_for_genomics_ror
"ehrStatus" | ehr_data_transfer
"sampleOrderStatus2ED02" |  
"sampleOrderStatus1PS08" |  
"sampleStatus2ED02" |  
"consentForWearStudy" |  
"race" | race_ethnicity
"onsiteIdVerificationType" |  
"onsiteIdVerificationVisitType" |  
"questionnaireOnPersonalAndFamilyHealthHistory" | personal_and_family_hx_ppi_survey_complete
"questionnaireOnDnaProgram" | program_update
"sampleStatus2ED04" |  
"sample1SAL2CollectionMethod" | saliva_collection
"questionnaireOnCopeVaccineMinute4" | new_year_minute_ppi_survey_complete
"questionnaireOnTheBasics" | basics_ppi_survey_complete
"genderIdentity" | gender_identity
"questionnaireOnCopeVaccineMinute3" | winter_minute_ppi_survey_complete
"deceasedStatus" | deceased
"biospecimenStatus" |  
"sampleStatus1SS08" |  
"consentForDvElectronicHealthRecordsSharing" | dv_only_ehr_sharing_status
"questionnaireOnSocialDeterminantsOfHealth" | sdoh_ppi_survey_complete
"sampleStatus1CFD9" | cell_free_dna_collected
"sampleStatus1UR90" | urine_90_ml_collected
"sampleOrderStatus2SST8" |  
"sampleOrderStatusDV1SAL2" |  
"sampleStatus2PST8" |  
"questionnaireOnFamilyHealth" | family_ppi_survey_complete
"sampleStatus1SAL2" |  
"questionnaireOnCopeNov" | cope_nov_ppi_survey_complete
"sampleOrderStatus2PST8" |  
"clinicPhysicalMeasurementsCreatedSite" | clinic_physical_measurements_created_site
"clinicPhysicalMeasurementsFinalizedSite" | clinic_physical_measurements_finalized_site
"biospecimenSourceSite" | biospecimens_location
"biospecimenCollectedSite" |  
"biospecimenProcessedSite" |  
"biospecimenFinalizedSite" |  
"site" |  
"enrollmentSite" | enrollment_site
"physicalMeasurementsStatus" | physical_measurements_status
"physicalMeasurementsCreatedSite" |  
"physicalMeasurementsFinalizedSite" |  
"physicalMeasurementsCollectType" | physical_measurements_collect_type
"relatedParticipants" |  
"isPediatric" |  
"questionnaireOnEnvironmentalHealth" |  
"remoteIdVerifiedOn" |  
"firstIdVerifiedOn" |  
"remoteIdVerificationOrigin" |

**Comment by NiviyaGeorge** [comment]
@ybushmanova, is all the fields listed out in the Api Field can be in the Database column? I see the "questionnaireOnBehavioralHealthAndPersonality" and"questionnaireOnEnvironmentalHealth" on the Api Field. We need those in our CSV export. Also, are those fields will have Date associated with when the questionnaire completed? If yes, we need date to be exported as well.

**Comment by ybushmanova** [comment]
@NiviyaGeorge yes, we can bring in any of those fields. I do not see questionnaireOnEnvironmentalHealth today but there is questionnaireOnEnvironmentalExposures? I hope it does not mean they chance API fields often.. I do not see associated date fields for this or other surveys in the payload. Where did you get the information about these fields and can we reach out to check if we can get to them?

**Comment by NiviyaGeorge** [comment]
@ybushmanova, I get this field from the DRC data dictionary. The questionnaire were released recently like July 2023. So they are appearing on HealthPro record as well.  This is where I get the field information: [Data Dictionary | Ops Data API](https://www.aoucollaborations.net/display/DRC/Data+Dictionary+%7C+Ops+Data+API)

**Comment by pshum1** [comment]
@NiviyaGeorge are all the fields in the table? Is there anything else we haven't looked at?

**Comment by NiviyaGeorge** [comment]
@pshum1, I think all the fields are in now. Thank you!
