### ISSUE TITLE
Look into error messages

### ISSUE THREAD

**Issue by lmkw** [NUARIG/all-of-us-helper#283]
A RestClient::UnprocessableEntity occurred in background at 2024-08-19 09:49:25 UTC :
  422 Unprocessable Entity
  /var/www/apps/all-of-us-helper/shared/bundle/ruby/3.2.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
 
[production]  (RestClient::UnprocessableEntity) "422 Unprocessable Entity" in AllOfUs

**Comment by pshum1** [comment]
Validation errors coming from ST API:

422 Unprocessable Entity{\"errors\":\"Validation failed: Subject NMHC Record Number is invalid\"}
422 Unprocessable Entity{\"errors\":\"PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block\\n\"}

Record numbers manually searchable in ST
